services:
  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"   # optional (for Mongo Compass)
    volumes:
      - mongo_data:/data/projectdb


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: notesapi:latest
    container_name: NotesAPI
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB_NAME: projectdb
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}
      SERPER_API_KEY: ${SERPER_API_KEY:-}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL:-}
      SMTP_USE_TLS: ${SMTP_USE_TLS:-true}
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo_data: